name: Run Tests in Jest
  # You may pin to the exact commit or the version.
  # uses: jlndk/github-action-jest@143c2a32fef8ca5583cd0ed8049c2c34b547b023
on:
  push:
    branches:
    - 'main'

jobs: 
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: use Node.js
        uses: actions/setup-node@v2
        with: 
          cache: 'npm'
          cache-dependency-path: SeniorProjectApp/package-lock.json
      - name: npm install
        run: npm ci
      - name: Tests
        run: npm test

      
      
